### ISSUE TITLE
Check compatibility with latest BP and WP

### ISSUE THREAD

**Issue by Stiofan** [GeoDirectory/buddypress-compliments#33]
Test with latest BP and WP.
I think a user complained there was no way to undo a compliment but i forget if we have this functionality or not, please check.

**Comment by picocodes** [comment]
@Stiofan on it

**Comment by picocodes** [comment]
Seems like only admins can delete complements. I'm pushing a fix that allows normal users to delete their own compliments

**Comment by 1naveengiri** [comment]
This issue is fixed and merged in master. 
closing the issue here.
