### ISSUE TITLE
Display "Send Compliments" button on another page

### ISSUE THREAD

**Issue by fabianschultz** [GeoDirectory/buddypress-compliments#47]
Hi, thanks so much for advancing the plugin, you did a fantastic job ;)

Can I ask if it is possible to add/display the "Send Compliments" button on another page as well so that once clicked, it has the same functionality (opening a modal and letting users decide which icon to seleect and then send it)?

Right now I have the button on a user profile page inside BuddyBoss platform -which is the default purpose/location of of the plugin.

However, it would be amazing to also be able to use the "Send Compliments" function/button somewhere else.

Any suggestion?

**Comment by Stiofan** [comment]
We are no longer supporting this plugin.
